server:
  port: 8080

spring:
  application:
    name: BANKING-SYSTEM
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/banking_db
    username: root
    password: Ramesh@2002
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

jwt:
  secret: bankingsystemsecretkey1234567890abcdefghij
  expiration: 86400000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true